In [15]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell 
InteractiveShell.ast_node_interactivity = 'all' #默认为'last'

<div class="jumbotron">
    <h1 class="display-1">Numpy</h1>
    <hr class="my-4">
    <p>主讲：李岩</p>
    <p>管理学院</p>
    <p>liyan@cumtb.edu.cn</p>
</div>

- NumPy是一个功能强大的Python库，主要用于对多维数组执行计算

- NumPy这个词来源于两个单词：Numerical和Python

- NumPy对于执行各种数学任务非常有用，如数值积分、微分、内插、外推等，是一种基于Python的MATLAB的快速替代

- Numpy快速入门教程 [https://www.numpy.org.cn/user/quickstart.html](https://www.numpy.org.cn/user/quickstart.html)

## 导入Numpy

```python
import numpy as np
```

In [2]:
np.nan
np.inf

nan

inf

## 数组

```python
numpy.array(list/tuple)
```

In [3]:
np.array((1,2,3,4,5))

array([1, 2, 3, 4, 5])

In [4]:
np.array([(1,2,3),(4,5,6)])

array([[1, 2, 3],
       [4, 5, 6]])

## `linspace()`函数 ，生成等差数列

```python
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False)
```

- `stop`：如果`endpoint=False`，结束值不包含在数列中

- `num`：要生成的等步长的样本数量

- `retstep`：如果为 True 时，生成的数组中会显示间距

In [11]:
np.linspace(2, 10, num=5, retstep=True)
np.linspace(2, 10, num=5, retstep=False)
np.linspace(2, 10, num=5, endpoint=False, retstep=True)

(array([ 2.,  4.,  6.,  8., 10.]), 2.0)

array([ 2.,  4.,  6.,  8., 10.])

(array([2. , 3.6, 5.2, 6.8, 8.4]), 1.6)

## `logspace()`函数，生成等比数列

```python
numpy.logspace(start, stop, num=50, endpoint=True, base=10.0)
```

- `base`：对数 log 的底数

In [6]:
np.logspace(0,9,10,base=2)

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

## `zeros()`函数

```python
numpy.zeros(shape, dtype = float)
```

In [14]:
np.zeros((2,2))
np.zeros(2)
np.zeros((2,2,2))

array([[0., 0.],
       [0., 0.]])

array([0., 0.])

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

## `ones()`函数

```python
numpy.ones(shape, dtype = float)
```

In [8]:
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

## `random`，创建随机数矩阵 

```python
numpy.random.random(shape)
```

- 创建取值在`[0, 1)`之间的随机数组

In [9]:
np.random.random([3,3])

array([[9.83949166e-01, 6.68374316e-04, 8.81360299e-01],
       [3.20693237e-01, 7.02417441e-01, 6.18790850e-01],
       [1.49011146e-01, 7.24224116e-01, 5.59054341e-02]])